version: "3"

dotenv: [".env"]

tasks:
  up:
    cmds:
      - docker compose up -d
    deps:
      - build

  up-a:
    cmds:
      - docker compose up
    deps:
      - build

  down:
    cmds:
      - docker compose down

  build:
    cmds:
      - docker compose build
    sources:
      - cmd/**/*.go
      - internal/**/*
      - Dockerfile
      - .env

  psql:
    cmds:
      - docker compose exec db psql -h localhost -d $POSTGRES_USER -U $POSTGRES_USER
