name: Discord Notification on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            ${{ github.event.pull_request.html_url }}
