name: Discord Notification on PR

on:
  pull_request:
    types: [opened]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            ${{ github.actor }}さんが以下のPRを出しました。
            ${{ github.event.pull_request.html_url }}
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.body }}
