name: Go Build Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Go version from go.mod
        id: goversion
        run: echo "::set-output name=version::$(grep 'go ' go.mod | awk '{print $2}')"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.goversion.outputs.version }}

      - name: Get dependencies
        run: go mod download

      - name: Format Go code
        run: go fmt ./...

      - name: Lint Go code
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
          golangci-lint run

      - name: Build
        run: go build -v ./...
